### ISSUE TITLE
Live site link is not longer good

### ISSUE THREAD

**Issue by SaintPeter** [HermanDhillon/DLscan#8]
I attempted to visit the live version of this site at http://dlscan.netlify.com/ but get a 404 error.

Was able to run it locally, though.

**Comment by HermanDhillon** [comment]
Thank you for creating this issue, The readme has been updated to include the new url : [https://dlscan.netlify.app/](https://dlscan.netlify.app/). It appears Netlify has changed the way they name their sub domains for user apps.
